package com.aaria.app.intelligence.incoming

class AbbreviationExpander {

    private val dictionary = mutableMapOf(
        // ── Hinglish core ──────────────────────────────────────────────────────
        "h" to "hai",
        "haan" to "haan",
        "nahi" to "nahi",
        "nhi" to "nahi",
        "nh" to "nahi",
        "na" to "nahi",
        "ha" to "haan",
        "yr" to "yaar",
        "yar" to "yaar",
        "bhai" to "bhai",
        "bro" to "bhai",
        "dost" to "dost",
        "kal" to "kal",
        "aaj" to "aaj",
        "abhi" to "abhi",
        "thik" to "theek",
        "thk" to "theek",
        "tk" to "theek",
        "hn" to "haan",
        "kya" to "kya",
        "kyu" to "kyun",
        "kyun" to "kyun",
        "kaise" to "kaise",
        "kab" to "kab",
        "kahan" to "kahan",
        "kha" to "kahan",
        "mat" to "mat",
        "bas" to "bas",
        "bol" to "bol",
        "sun" to "sun",
        "dekh" to "dekh",
        "aa" to "aa",
        "ja" to "ja",
        "le" to "le",
        "de" to "de",
        "kar" to "kar",
        "reh" to "reh",
        "chal" to "chal",
        "chalo" to "chalo",
        "accha" to "accha",
        "acha" to "accha",
        "sahi" to "sahi",
        "galat" to "galat",
        "pata" to "pata",
        "pta" to "pata",
        "bata" to "bata",
        "btao" to "batao",
        "batao" to "batao",
        "lol" to "haha",
        "haha" to "haha",
        "hehe" to "hehe",
        "xd" to "haha",
        "lmao" to "haha",
        "lmfao" to "haha",
        // ── WhatsApp Hinglish shorthand ────────────────────────────────────────
        "m" to "main",
        "mai" to "main",
        "mein" to "main",
        "tu" to "tu",
        "tum" to "tum",
        "aap" to "aap",
        "vo" to "woh",
        "woh" to "woh",
        "hm" to "hum",
        "hum" to "hum",
        "sb" to "sab",
        "sab" to "sab",
        "koi" to "koi",
        "kuch" to "kuch",
        "kch" to "kuch",
        "bahut" to "bahut",
        "bhut" to "bahut",
        "bht" to "bahut",
        "thoda" to "thoda",
        "thodi" to "thodi",
        "zyada" to "zyada",
        "jyada" to "zyada",
        "kam" to "kam",
        "jaldi" to "jaldi",
        "dhire" to "dheere",
        "ruk" to "ruk",
        "wait" to "wait",
        "ok" to "ok",
        "okay" to "okay",
        "k" to "ok",
        "hm" to "hmm",
        "hmm" to "hmm",
        "arre" to "arre",
        "are" to "arre",
        "oye" to "oye",
        "yaar" to "yaar",
        "bhai" to "bhai",
        "didi" to "didi",
        "bhaiya" to "bhaiya",
        "ji" to "ji",
        "hnji" to "haan ji",
        "hnj" to "haan ji",
        "nj" to "nahi ji",
        // ── English shorthand ──────────────────────────────────────────────────
        "srsly" to "seriously",
        "tbh" to "to be honest",
        "brb" to "be right back",
        "btw" to "by the way",
        "ngl" to "not gonna lie",
        "idk" to "I don't know",
        "idc" to "I don't care",
        "imo" to "in my opinion",
        "imho" to "in my honest opinion",
        "bc" to "because",
        "bcoz" to "because",
        "coz" to "because",
        "rn" to "right now",
        "nvm" to "never mind",
        "ig" to "I guess",
        "omw" to "on my way",
        "omg" to "oh my god",
        "wtf" to "what the",
        "wth" to "what the heck",
        "fyi" to "for your information",
        "asap" to "as soon as possible",
        "irl" to "in real life",
        "dm" to "direct message",
        "msg" to "message",
        "msgs" to "messages",
        "pls" to "please",
        "plz" to "please",
        "plss" to "please",
        "thx" to "thanks",
        "ty" to "thank you",
        "tyvm" to "thank you very much",
        "np" to "no problem",
        "nw" to "no worries",
        "yw" to "you're welcome",
        "gr8" to "great",
        "b4" to "before",
        "2day" to "today",
        "2moro" to "tomorrow",
        "2nite" to "tonight",
        "ur" to "your",
        "u" to "you",
        "r" to "are",
        "wanna" to "want to",
        "gonna" to "going to",
        "gotta" to "got to",
        "kinda" to "kind of",
        "sorta" to "sort of",
        "cmon" to "come on",
        "c'mon" to "come on",
        "lemme" to "let me",
        "gimme" to "give me",
        "dunno" to "don't know",
        "smh" to "shaking my head",
        "fr" to "for real",
        "frfr" to "for real for real",
        "lowkey" to "lowkey",
        "highkey" to "highkey",
        "gg" to "good game",
        "gl" to "good luck",
        "hf" to "have fun",
        "wb" to "welcome back",
        "gtg" to "got to go",
        "g2g" to "got to go",
        "bbl" to "be back later",
        "ttyl" to "talk to you later",
        "ttys" to "talk to you soon",
        "cya" to "see you",
        "cu" to "see you",
        "tc" to "take care"
    )

    fun expand(text: String): String {
        // Split on whitespace, preserving the whitespace tokens so we can rejoin exactly
        val tokens = text.split(Regex("(?<=\\s)|(?=\\s)"))
        return tokens.joinToString("") { token ->
            val trimmed = token.trim()
            if (trimmed.isEmpty()) token
            else {
                // Strip trailing punctuation before dictionary lookup, re-attach after
                val trailingPunct = trimmed.takeLastWhile { it in PUNCT_CHARS }
                val word = if (trailingPunct.isNotEmpty()) trimmed.dropLast(trailingPunct.length) else trimmed
                val expanded = dictionary[word.lowercase()]
                if (expanded != null) {
                    val result = if (word[0].isUpperCase()) expanded.replaceFirstChar { it.uppercase() }
                                 else expanded
                    result + trailingPunct
                } else token
            }
        }
    }

    companion object {
        private val PUNCT_CHARS = setOf('.', ',', '!', '?', ';', ':', '…')
    }

    fun addCustomExpansion(abbreviation: String, expansion: String) {
        dictionary[abbreviation.lowercase()] = expansion
    }
}
